/**:
    ros__parameters:
        image_transport: raw    # image format
        family: 25h9            # tag family name
        size: 0.2  #0.173             # tag edge size in meter
        max_hamming: 0          # maximum allowed hamming distance (corrected bits)
        qos_profile: sensor_data    # optional qos_profile, "sensor_data", "default", or "system_default"

        # see "apriltag.h" 'struct apriltag_detector' for more documentation on these optional parameters
        detector:
            threads: 2          # number of threads
            decimate: 1.0       # decimate resolution for quad detection
            blur: 0.0           # sigma of Gaussian blur for quad detection
            refine: True        # snap to strong gradients
            sharpening: 0.25    # sharpening of decoded images
            debug: False        # write additional debugging images to current working directory


        pose_estimation_method: "pnp"   # method for estimating the tag pose

        # optional list of tags
        tag:
            ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]            # tag ID
            frames: [tag_0, tag_1, tag_2, tag_3, tag_4, tag_5, tag_6, tag_7, tag_8, tag_9, tag_10]
            sizes:  [0.20, 0.20, 0.20, 0.20, 0.20, 0.20, 0.20, 0.20, 0.20, 0.20, 0.20]

